stages:
  - semantic-release
  - publish
  - build
  - semantic-release-helm
  - deploy

include:
  - local: jupyterlab-gpu-image/.gitlab-ci.yml
  - local: vscode/.gitlab-ci.yml
  - local: mlflow/.gitlab-ci.yml
  - local: helm/.gitlab-ci.yml
