apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vscode
  name: vscode
spec:
  selector:
    matchLabels:
      app: vscode
  replicas: 1
  template:
    metadata:
      labels:
        app: vscode
    spec:
      containers:
      - image: codercom/code-server:v2
        imagePullPolicy: Always
        name: vscode
        env:
          - name: PASSWORD
            value: "{{ .Values.vscode.password }}"
        ports:
        - containerPort: 8080
          name: https
