apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vscode
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: code.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: vscode
              servicePort: http
