apiVersion: v1
kind: Service
metadata:
  name: vscode
  labels:
    app: vscode  
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: vscode
