apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000000m"

spec:
  rules:
    - host: minio.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-minio
              servicePort: 9000
          - path: /listener
            backend:
              serviceName: autologin
              servicePort: http
