apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000000m"

spec:
  {{ if .Values.tls.enable -}}
  tls:
    - hosts:
        - minio.{{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls-secret
  {{- end }}
  rules:
    - host: minio.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-minio
              servicePort: 9000
