deploy-docs-site:
  stage: publish
  image: node
  variables:
    HUGO_VERSION: "0.66.0"
    HUGO_TYPE: "_extended"
    GITHUB_PUBLISH_TOKEN: $GITHUB_PUBLISH_TOKEN
  before_script:
    - export HUGO_ID="hugo${HUGO_TYPE}_${HUGO_VERSION}"
    - curl -sL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_ID}_Linux-64bit.tar.gz
        -o /tmp/${HUGO_ID}_Linux-64bit.tar.gz
        && tar -xf /tmp/${HUGO_ID}_Linux-64bit.tar.gz -C /tmp
        && mkdir -p /usr/local/sbin
        && mv /tmp/hugo /usr/local/sbin/hugo
        && rm -rf /tmp/${HUGO_ID}_linux_amd64
        && rm -rf /tmp/${HUGO_ID}_Linux-64bit.tar.gz
    # install theme submodules and dependencies
    - npm install --prefix docs-site
    - git submodule init
      && git submodule update --init --recursive
    # Setup git pointing to Github Pages branch
    -  mkdir /tmp/gh-pages
      && (cd /tmp/gh-pages
        && git init
        && git config --global user.email "${GITLAB_USER_EMAIL}"
        && git config --global user.name "${GITLAB_USER_NAME}"
        && git remote add upstream https://${GITHUB_PUBLISH_USERNAME}:${GITHUB_PUBLISH_TOKEN}@github.com/intelygenz/science-toolkit.git
        && git fetch upstream
        && git checkout gh-pages)
  script:
    # Generate site
    - cd docs-site && hugo -d /tmp/gh-pages -c ../docs

    # Commit & Publish site
    - cd /tmp/gh-pages
      && git add .
      && git commit -m "publish docs pages from commit ${CI_COMMIT_SHORT_SHA}"
      && git push upstream gh-pages:gh-pages --force
  only:
    refs:
      - master
    changes:
      - docs/**/*
      - docs-site/**/*
