release-jupyterlab-gpu-image:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix jupyterlab-gpu-image
  script:
    - cd jupyterlab-gpu-image && npx semantic-release -e semantic-release-monorepo
  only:
    changes:
      - jupyterlab-gpu-image/**/*
    refs:
      - master

publish_docker_image:
  stage: publish
  image: docker:18-git
  services:
    - docker:18-dind
  tags:
    - dind
  variables:
    PROJECT_GROUP: "terminus7"
    IMAGE_PROJECT_NAME: "jupyterlab-gpu"
  before_script:
    - apk add bash git coreutils --update
    - docker login -u $DOCKER_CLOUD_USER -p $DOCKER_CLOUD_PASS docker.io
  script:
    - cd jupyterlab-gpu-image
    - export TAG=${CI_COMMIT_TAG#jupyterlab-gpu-image-v}
    - docker build -t $PROJECT_GROUP/$IMAGE_PROJECT_NAME:$TAG .
    - docker push $PROJECT_GROUP/$IMAGE_PROJECT_NAME:$TAG
  after_script:
    - docker rmi $PROJECT_GROUP/$IMAGE_PROJECT_NAME:$TAG
  only:
    - /^jupyterlab-gpu-image-v\d*.\d*.\d*$/
