apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "codeserver.fullname" . }}
  labels:
{{ include "codeserver.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.username }}-code.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "codeserver.fullname" . }}
              servicePort: http

