apiVersion: v1
kind: Service
metadata:
  name: {{ include "codeserver.fullname" . }}
  labels:
{{ include "codeserver.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codeserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
