release-vscode-operator:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix vscode-operator
  script:
    - cd vscode-operator && npx semantic-release -e semantic-release-monorepo
  only:
    refs:
      - master
    changes:
      - vscode/**/*
      - vscode-operator/**/*
      - .gitlab-ci.yml

publish-vscode-operator-image:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    SDK_RELEASE_VERSION: v0.15.1
    HELM_VERSION: v3.1.1
    IMAGE_PROJECT_NAME: "terminus7/sci-toolkit-vscode-operator"
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
    README_FILEPATH: "./vscode-operator/README.md"
    TAGS_VERSION: 1.0.0
    COMPONENT_TAGS_PROJECT_ID: "intelygenz/science-toolkit"
  before_script:
    - apk add curl jq bash gettext git coreutils --update
    - wget -q https://github.com/guumaster/monorepo-components-tags/releases/download/v${TAGS_VERSION}/monorepo-components-tags_${TAGS_VERSION}_linux_64-bit.tar.gz -O - | tar -xzO  monorepo-components-tags >  /usr/local/bin/monorepo-components-tags
    - chmod +x /usr/local/bin/monorepo-components-tags
    - /usr/local/bin/monorepo-components-tags --project $COMPONENT_TAGS_PROJECT_ID --commit $CI_COMMIT_SHA --export-shell --suffix TAG --provider GITHUB | tee -a /tmp/components_tags.sh
    - source /tmp/components_tags.sh
    - ./scripts/replace_env_path.sh
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - cd vscode-operator
    - ./scripts/install_operator_sdk.sh
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm dependency update helm-charts/codeserver
  script:
    - TAG=${CI_COMMIT_TAG#vscode-operator-v}
    - operator-sdk build $IMAGE_PROJECT_NAME:$TAG
    - docker tag $IMAGE_PROJECT_NAME:$TAG $IMAGE_PROJECT_NAME:latest
    - docker push $IMAGE_PROJECT_NAME:$TAG
    - docker push $IMAGE_PROJECT_NAME:latest
    - cd ..
    - ./scripts/update-dockerhub-readme.sh
  after_script:
    - docker rmi $IMAGE_PROJECT_NAME:$TAG
  only:
    refs:
      - /^vscode-operator-v\d*.\d*.\d*$/
