apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codeservers.sci-toolkit.konstellation.io
spec:
  group: sci-toolkit.konstellation.io
  names:
    kind: CodeServer
    listKind: CodeServerList
    plural: codeservers
    singular: codeserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
