domain: toolkit.local

kdl:
  enabled: false

ingress:
  type: "nginx"

username: user.name

usernameSlug: user-name

storage:
  size: 10Gi
  className: standard

sharedVolume:
  name: ""

tls: false

oauth2Proxy:
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.0.1-amd64
    pullPolicy: IfNotPresent
