apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: drone
  labels:
    app:  drone
spec:
  {{ if .Values.tls.enable -}}
  tls:
    - hosts:
        - drone.{{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls-secret
  {{- end }}
  rules:
    - host: drone.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: drone
              servicePort: http
