{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: drone
  annotations:
    {{ if eq .Values.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
    {{ end }}
  labels:
    app:  drone
spec:
  {{ if .Values.tls.enabled -}}
  tls:
    - hosts:
        - drone.{{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls-secret
  {{- end }}
  rules:
    - host: drone.{{ .Values.domain }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: drone
                port:
                  number: 80
          {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
          - path: /
            backend:
              serviceName: drone
              servicePort: http
          {{ end }} 
