apiVersion: v1
kind: Service
metadata:
  name: drone-secrets-plugin
  labels:
    app: drone-secrets-plugin
spec:
  clusterIP: None
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: drone-secrets-plugin
