apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "user-tools.fullname" . }}
  labels:
{{ include "user-tools.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - {{ .Values.usernameSlug }}-code.{{ .Values.domain }}
        - {{ .Values.usernameSlug }}-jupyter.{{ .Values.domain }}
      secretName: {{ .Release.Name }}-tls-secret
  rules:
    - host: {{ .Values.usernameSlug }}-code.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "user-tools.fullname" . }}-code
              servicePort: http
    - host: {{ .Values.usernameSlug }}-jupyter.{{ .Values.domain }}
      http:
        paths:
            - path: /
              backend:
                serviceName: {{ include "user-tools.fullname" . }}-jupyter
                servicePort: http
