apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-tools.fullname" . }}-oauth2-proxy
data:
  oauth2_proxy.cfg: |+
    provider="gitea"
    cookie_secret="_csrf"
    login_url="https://gitea.{{ .Values.domain }}/login/oauth/authorize"
    redeem_url="https://gitea.{{ .Values.domain }}/login/oauth/access_token"
    profile_url="https://gitea.{{ .Values.domain }}/api/v1/user"
    cookie_secure=true
    cookie_samesite="none"
    ssl_insecure_skip_verify=true
    ssl_upstream_insecure_skip_verify=true
