apiVersion: v1
appVersion: "1.0"
description: Science Toolkit
name: science-toolkit
version: 0.1.0
dependencies:
  - name: jupyterhub
    version: "0.9.0-beta.3"
    repository: https://jupyterhub.github.io/helm-chart/
  - name: minio
    version: "2.5.16"
    repository: "@stable"