apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-init
  labels:
    app:  gitea-init
data:
  app.ini: |+
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    RUN_USER = git

    [repository]
    ROOT = /data/git/repositories

    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    APP_DATA_PATH    = /data/gitea
    SSH_DOMAIN       = gitea.{{ .Values.domain }}
    HTTP_PORT        = 3000
    ROOT_URL         = http://gitea.{{ .Values.domain }}/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    SSH_LISTEN_PORT  = 22
    LFS_START_SERVER = true
    LFS_CONTENT_PATH = /data/git/lfs
    DOMAIN           = gitea.{{ .Values.domain }}
    LFS_JWT_SECRET   = dJd7zxw11VRhqCighcaeLvUbxlDC45IK2VNc4TCsZc8
    OFFLINE_MODE     = false

    [database]
    PATH     = /data/gitea/gitea.db
    DB_TYPE  = postgres
    HOST     = postgres:5432
    NAME     = gitea
    USER     = postgres
    PASSWD   = test
    SSL_MODE = disable
    CHARSET  = utf8

    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER        = file

    [picture]
    AVATAR_UPLOAD_PATH            = /data/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /data/gitea/attachments

    [log]
    ROOT_PATH = /data/gitea/log
    MODE      = file
    LEVEL     = info

    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     = F0x0GV8YmJ02wVzDBUKldlCPnnt4xWIDi41Bp3nYc1pJac0gKnZdU3lELku14ebk
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1ODIwMjM5OTN9.hhV2-a4NWxdtq7zRvN-LN166ap9TAKnrHy0h-qHt5Do

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.example.org

    [oauth2]
    JWT_SECRET = 26235oZvtjxLx1AKdXiDUQvQGIDU2L7vhTakiY7zKEg

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true

