apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitea
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - gitea.{{ .Values.domain }}
      secretName: {{ .Release.Name }}-tls-secret
  rules:
    - host: gitea.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: gitea
              servicePort: http
