{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: gitea
  annotations:
    {{ if eq .Values.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
    {{ end }}
spec:
  {{ if .Values.tls.enabled -}}
  tls:
    - hosts:
        - gitea.{{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls-secret
  {{- end }}
  rules:
    - host: gitea.{{ .Values.domain }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gitea
                port:
                  number: 80
          {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
          - path: /
            backend:
              serviceName: gitea
              servicePort: http
          {{ end }} 
