apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.gitea.service.port }}
      protocol: TCP
    - name: ssh
      port: 2222
      targetPort: 22
      protocol: TCP
  selector:
    app: gitea
