apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gitea
  labels:
    app:  gitea
spec:
  serviceName: "gitea"
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: gitea
          image: {{ .Values.gitea.image.repository }}:{{ .Values.gitea.image.tag }}
          imagePullPolicy: {{ .Values.gitea.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: gitea-config
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/su"
                  - "git"
                  - "-c"
                  - "/usr/local/bin/create-admin.sh"
          volumeMounts:
            - name: gitea-pvc
              mountPath: /data
            - name: gitea-init
              mountPath: /data/gitea/conf/app.ini
              subPath: app.ini
            - name: gitea-init
              mountPath: /usr/local/bin/create-admin.sh
              subPath: create-admin.sh
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
      volumes:
        - name: gitea-init
          configMap:
            name: gitea-init
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: gitea-pvc
        labels:
          app: gitea
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.gitea.storage.storageClassName }}
        resources:
          requests:
            storage:  {{ .Values.gitea.storage.size }}