apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sci-toolkit-ingresss
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:

    - host: minio.toolkit.local
      http:
        paths:
          - path: /
            backend:
              serviceName: minio
              servicePort: 9000
          - path: /listener
            backend:
              serviceName: autologin
              servicePort: http

    - host: gitea.{{ .Values.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: gitea
              servicePort: http
          - path: /listener
            backend:
              serviceName: autologin
              servicePort: http

    - host: jupyter.{{ .Values.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: proxy-public
              servicePort: http
          - path: /listener
            backend:
              serviceName: autologin
              servicePort: http

    - host: drone.{{ .Values.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: drone-drone
              servicePort: http
          - path: /listener
            backend:
              serviceName: autologin
              servicePort: http


    - host: app.{{ .Values.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: autologin
              servicePort: http
