{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ .Values.mlflow.name }}-ingress
  labels:
    app:  {{ .Values.mlflow.name }}
spec:
  {{ if .Values.tls.enabled -}}
  tls:
    - hosts:
        - {{ .Values.mlflow.host }}.{{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls-secret
  {{- end }}
  rules:
    - host: {{ .Values.mlflow.host }}.{{ .Values.domain }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.mlflow.name }}
                port:
                  number: 8080
          {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
          - path: /
            backend:
              serviceName: {{ .Values.mlflow.name }}
              servicePort: 8080
          {{ end }} 
