apiVersion: v1
kind: Secret
metadata:
  name: mlflow-oauth2-secrets
type: Opaque
data:
  DEPLOYMENT_SECRET_NAME: {{ print "mlflow-oauth2-secrets" | b64enc }}
  OAUTH2_CREDENTIALS_PREFIX: {{ print "mlflow" | b64enc }}
  GITEA_REDIRECT_URIS: {{ printf "%s://mlflow.%s/oauth2/callback" ( include "protocol" . ) .Values.domain | b64enc }}
  GITEA_APPLICATION_NAME: {{ print "mlflow" | b64enc }}
  MLFLOW_OAUTH2_CALLBACK_URL: {{ printf "$s://mlflow.%s/oauth2/callback" ( include "protocol" . ) .Values.domain | b64enc }}
  MLFLOW_OAUTH2_INITIALIZED: {{ print "no" | b64enc }}
