apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mlflow.name }}
  labels:
    app: {{ .Values.mlflow.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mlflow.service.port }}
      targetPort: {{ .Values.mlflow.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.mlflow.name }}
