release-helm-chart:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install -g semantic-release@15.14.0 semantic-release/github
  script:
    - semantic-release -t helm-chart-v\${version}
  only:
    refs:
      - master
    changes:
      - helm/**/*

release-helm-after-image:
  stage: semantic-release-helm
  image: node:10
  before_script:
    - npm install -g semantic-release@15.14.0 semantic-release/github
  script:
    - semantic-release -t helm-chart-v\${version} -b $CI_COMMIT_TAG
  only:
    - tags
  except:
    - /^helm-chart-v\d*.\d*.\d*$/

generate-helm-chart:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    HELM_VERSION: v3.1.1
    GITHUB_TOKEN: $GITHUB_TOKEN
    COMPONENT_TAGS_PROJECT_ID: "intelygenz/science-toolkit"
  before_script:
    - export DOCKER_COMMAND="docker run
      -v $CI_PROJECT_DIR:/app
      -w /app
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
    - apk add --update bash gettext coreutils git
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - wget -q https://gitlab-components-tags.s3.amazonaws.com/gitlab-components-tags -O /usr/local/bin/gitlab-components-tags
    - chmod +x /usr/local/bin/gitlab-components-tags
    - /usr/local/bin/gitlab-components-tags --project $COMPONENT_TAGS_PROJECT_ID --commit $CI_COMMIT_SHA --export-shell --provider GITHUB
    - eval $(/usr/local/bin/gitlab-components-tags --project $COMPONENT_TAGS_PROJECT_ID --commit $CI_COMMIT_SHA --export-shell --provider GITHUB)
    - ./scripts/replace_env_path.sh
  script:
    - export CHART_VERSION=${CI_COMMIT_TAG#helm-chart-v}
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm dep update helm/science-toolkit
    - helm package helm/science-toolkit --version $CHART_VERSION
    - $DOCKER_COMMAND mesosphere/aws-cli s3 cp science-toolkit-$CHART_VERSION.tgz s3://science-toolkit-helm-charts/science-toolkit-$CHART_VERSION.tgz
  artifacts:
    when: on_failure
    paths:
      - helm
  only:
    refs:
      - /^helm-chart-v\d*.\d*.\d*$/

generate-helm-lite-chart:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    HELM_VERSION: v3.1.1
    GITHUB_TOKEN: $GITHUB_TOKEN
    COMPONENT_TAGS_PROJECT_ID: "intelygenz/science-toolkit"
  before_script:
    - export DOCKER_COMMAND="docker run
      -v $CI_PROJECT_DIR:/app
      -w /app
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
    - apk add --update bash gettext coreutils git
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - wget -q https://gitlab-components-tags.s3.amazonaws.com/gitlab-components-tags -O /usr/local/bin/gitlab-components-tags
    - chmod +x /usr/local/bin/gitlab-components-tags
    - /usr/local/bin/gitlab-components-tags --project $COMPONENT_TAGS_PROJECT_ID --commit $CI_COMMIT_SHA --export-shell --provider GITHUB
    - eval $(/usr/local/bin/gitlab-components-tags --project $COMPONENT_TAGS_PROJECT_ID --commit $CI_COMMIT_SHA --export-shell --provider GITHUB)
    - ./scripts/replace_env_path.sh
  script:
    - export CHART_VERSION=${CI_COMMIT_TAG#helm-chart-v}
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm dep update helm/science-toolkit-lite
    - helm package helm/science-toolkit-lite --version $CHART_VERSION
    - $DOCKER_COMMAND mesosphere/aws-cli s3 cp science-toolkit-lite-$CHART_VERSION.tgz s3://science-toolkit-lite-helm-charts/science-toolkit-lite-$CHART_VERSION.tgz
  artifacts:
    when: on_failure
    paths:
      - helm
  only:
    refs:
      - /^helm-chart-v\d*.\d*.\d*$/
