release-helm-chart:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install -g semantic-release@15.14.0 semantic-release/github
  script:
    - semantic-release -t helm-chart-v\${version}
  only:
    refs:
      - master
    changes:
      - helm/**/*

release-helm-after-image:
  stage: semantic-release-helm
  image: node:10
  before_script:
    - npm install -g semantic-release@15.14.0 semantic-release/github
  script:
    - semantic-release -t helm-chart-v\${version} -b $CI_COMMIT_TAG
  only:
    - tags
  except:
    - /^helm-chart-v\d*.\d*.\d*$/

generate-helm-chart:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    HELM_VERSION: v3.1.1
  before_script:
    - export DOCKER_COMMAND="docker run
      -v $CI_PROJECT_DIR:/app
      -w /app
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
    - apk add --update bash gettext coreutils git
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - export VSCODE_TAG=$(./scripts/git_latest_tag.sh "vscode")
    - export DASHBOARD_TAG=$(./scripts/git_latest_tag.sh "dashboard")
    - export GITEA_OAUTH2_SETUP_TAG=$(./scripts/git_latest_tag.sh "gitea-oauth2-setup")
    - export JUPYTER_LAB_GPU_TAG=$(./scripts/git_latest_tag.sh "jupyterlab-gpu-image")
    - export MLFLOW_TAG=$(./scripts/git_latest_tag.sh "mlflow")
    - ./scripts/replace_env_path.sh
  script:
    - export CHART_VERSION=${CI_COMMIT_TAG#helm-chart-v}
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm dep update helm/science-toolkit
    - helm package helm/science-toolkit --version $CHART_VERSION
    - $DOCKER_COMMAND mesosphere/aws-cli s3 cp science-toolkit-$CHART_VERSION.tgz s3://science-toolkit-helm-charts/science-toolkit-$CHART_VERSION.tgz
  only:
    refs:
      - /^helm-chart-v\d*.\d*.\d*$/

generate-helm-lite-chart:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    HELM_VERSION: v3.1.1
  before_script:
    - export DOCKER_COMMAND="docker run
      -v $CI_PROJECT_DIR:/app
      -w /app
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
    - apk add --update bash gettext coreutils git
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - export JUPYTER_LAB_GPU_TAG=$(./scripts/git_latest_tag.sh "jupyterlab-gpu-image")
    - export MLFLOW_TAG=$(./scripts/git_latest_tag.sh "mlflow")
    - ./scripts/replace_env_path.sh
  script:
    - export CHART_VERSION=${CI_COMMIT_TAG#helm-chart-v}
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm dep update helm/science-toolkit-lite
    - helm package helm/science-toolkit-lite --version $CHART_VERSION
    - $DOCKER_COMMAND mesosphere/aws-cli s3 cp science-toolkit-lite-$CHART_VERSION.tgz s3://science-toolkit-lite-helm-charts/science-toolkit-lite-$CHART_VERSION.tgz
  only:
    refs:
      - /^helm-chart-v\d*.\d*.\d*$/

deploy-helm-dell:
  stage: deploy
  tags:
    - konstellation
  environment:
    name: int
  variables:
    HELM_VERSION: v3.1.1
  image: google/cloud-sdk:283.0.0
  script:
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - kubectl create ns science-toolkit --dry-run -o yaml | kubectl apply -f -
    - export CHART_VERSION=${CI_COMMIT_TAG#helm-chart-v}
    - aws s3 cp s3://science-toolkit-helm-charts/science-toolkit-$CHART_VERSION.tgz science-toolkit-$CHART_VERSION.tgz
    - ./scripts/replace_env_path.sh
    - helm upgrade
      --wait
      --install science-toolkit
      --namespace science-toolkit
      --values helm/values-dell.yaml
      --timeout 600
      science-toolkit-$CHART_VERSION.tgz
  only:
    refs:
      - /^helm-chart-v\d*.\d*.\d*$/
  when: manual

deploy-helm-lite-dell:
  stage: deploy
  tags:
    - konstellation
  environment:
    name: int
  variables:
    HELM_VERSION: v3.1.1
  image: google/cloud-sdk:283.0.0
  script:
    - wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
    - kubectl create ns science-toolkit-lite --dry-run -o yaml | kubectl apply -f -
    - export CHART_VERSION=${CI_COMMIT_TAG#helm-chart-v}
    - aws s3 cp s3://science-toolkit-lite-helm-charts/science-toolkit-lite-$CHART_VERSION.tgz science-toolkit-lite-$CHART_VERSION.tgz
    - ./scripts/replace_env_path.sh
    - helm upgrade
      --wait
      --install science-toolkit-lite
      --namespace science-toolkit-lite
      --values helm/values-dell-lite.yaml
      --timeout 600
      science-toolkit-lite-$CHART_VERSION.tgz
  only:
    refs:
      - /^helm-chart-v\d*.\d*.\d*$/
  when: manual

