{{ if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1" }}
apiVersion: apiextensions.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
apiVersion: apiextensions.k8s.io/v1beta1
{{ end }}
kind: CustomResourceDefinition
metadata:
  name: usertools.sci-toolkit.konstellation.io
spec:
  group: sci-toolkit.konstellation.io
  names:
    kind: UserTools
    listKind: UserToolsList
    plural: usertools
    singular: usertool
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    {{ if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1" }}
    schema:
      openAPIV3Schema:
        type: object
    {{ end }}