apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
    - host: jupyter.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: proxy-public
              servicePort: http

