apiVersion: v1
kind: Secret
metadata:
  name: jupyter-oauth2-secrets
type: Opaque
data:
  DEPLOYMENT_SECRET_NAME: {{ print "jupyter-oauth2-secrets" | b64enc }}
  OAUTH2_CREDENTIALS_PREFIX: {{ print "jupyter" | b64enc }}
  GITEA_REDIRECT_URIS: {{ printf "http://jupyter.%s/hub/oauth_callback" .Values.domain | b64enc }}
  GITEA_APPLICATION_NAME: {{ print "jupyter" | b64enc }}
  JUPYTER_OAUTH2_CALLBACK_URL: {{ printf "http://jupyter.%s/hub/oauth_callback" .Values.domain | b64enc }}
  JUPYTER_OAUTH2_INITIALIZED: {{ print "no" | b64enc }}
