kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oauth
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get","update","list", "create"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codeserver
rules:
  - apiGroups: ["sci-toolkit.konstellation.io"]
    resources: ["codeservers"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-oauth
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: oauth
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-oauth
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: oauth
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-codeserver
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: codeserver
  apiGroup: rbac.authorization.k8s.io
