apiVersion: v1
kind: Secret
metadata:
  name: tools-secret
  annotations:
    x-drone-events: push, tag
    x-drone-repos: *
  labels:
    app:  tools-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | b64enc }}
