apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub
  annotations:
    {{ if eq .Values.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
    {{ end }}

spec:
  rules:
    - host: jupyter.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: proxy-public
              servicePort: http
          - path: /listener
            backend:
              serviceName: autologin
              servicePort: http
